name: password_generator
description: "CipherForge: Secure Keysmith"
publish_to: "none"
version: 1.1.0+4

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true